---
- name: Install docker on the nodes by geerlingguy.docker
  hosts: webserver
  become: yes
  become_user: root

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.docker
    - geerlingguy.pip

