---
- name: Prepare webserver
  hosts: webserver
  
  tasks:
  - name: Down docker-compose.prod.yml
    ansible.builtin.command:
      cmd: /usr/local/bin/docker-compose -f /home/ubuntu/webserver/docker-compose.prod.yml down 
    ignore_errors: true

  - name: Docker system prune for cleaning
    ansible.builtin.command:
      cmd:  /usr/bin/docker system prune -f

  - name: Delete directory for cleaning
    ansible.builtin.file:
      path: /home/ubuntu/webserver
      state: absent  
        
  - name: Creates directory for git clone  
    ansible.builtin.file:
      path: /home/ubuntu/webserver
      state: directory
  
  - name: Git clone from master branch
    ansible.builtin.git:
      repo: https://github.com/dalpengholic/eficode-assignment-weatherapp.git
      dest: /home/ubuntu/webserver
      single_branch: yes
      version: master  

  - name: Copy .prod.env file 
    ansible.builtin.copy:
      src: ./.prod.env
      dest: /home/ubuntu/webserver

  - name: Pull and run docker-compose.prod.yml
    ansible.builtin.command: "{{ item }}"
    with_items:
      - /usr/local/bin/docker-compose -f /home/ubuntu/webserver/docker-compose.prod.yml pull
      - /usr/local/bin/docker-compose -f /home/ubuntu/webserver/docker-compose.prod.yml up -d

   # name: Run docker-compose.prod.yml
    #ansible.builtin.command:
      # cmd: /usr/local/bin/docker-compose -f /home/ubuntu/webserver/docker-compose.prod.yml up -d
